[build]
builder = "nixpacks"
buildCommand = "pip install -r model/requirements.txt && pip install uvicorn"

[deploy]
startCommand = "cd model && python -m uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100

[deploy.worker]
startCommand = "cd model && python scheduler.py" 